project 'QRPassword.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRPassword' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'CryptoSwift'
  pod 'SQLite.swift','~> 0.11.5'
  pod 'SwiftyJSON'
end
